MilitaryRank.create(name: 'Civil', abbreviation: 'CV')
MilitaryRank.create(name: 'Soldado', abbreviation: 'SD')
MilitaryRank.create(name: 'Cabo', abbreviation: 'CB')
MilitaryRank.create(name: '3º Sargento', abbreviation: '3º SGT')
MilitaryRank.create(name: '2º Sargento', abbreviation: '2º SGT')
MilitaryRank.create(name: '1º Sargento', abbreviation: '1º SGT')
MilitaryRank.create(name: 'Subtenente', abbreviation: 'ST')
MilitaryRank.create(name: 'Cadete 1º Ano', abbreviation: 'CFO 1º')
MilitaryRank.create(name: 'Cadete 2º Ano', abbreviation: 'CFO 2º')
MilitaryRank.create(name: 'Cadete 3º Ano', abbreviation: 'CFO 3º')
MilitaryRank.create(name: 'Aspirante-Oficial', abbreviation: 'ASP')
MilitaryRank.create(name: '2º Tenente', abbreviation: '2º TEN')
MilitaryRank.create(name: '1º Tenente', abbreviation: '1º TEN')
MilitaryRank.create(name: 'Capitão', abbreviation: 'CAP')
MilitaryRank.create(name: 'Major', abbreviation: 'MAJ')
MilitaryRank.create(name: 'Tenente Coronel', abbreviation: 'TC')
MilitaryRank.create(name: 'Coronel', abbreviation: 'CEL')
MilitaryRank.create(name: 'Soldado Rec', abbreviation: 'REC')
MilitaryRank.create(name: 'Aluno CFC', abbreviation: 'AL CFC')
MilitaryRank.create(name: 'Aluno CFS', abbreviation: 'AL SGT')
